---
# Section 1 Fixes
- name: "NOTSCORED | 1.1 | AUDIT | Ensure the Pre-Installation Planning Checklist Has Been Implemented"
  debug:
      msg:
          - "Warning! Make sure you have your pre-installation checklist completed"
          - "Please refer to control 1.1 in the benchmark document for those items"
  when:
      - apache_cis_1_1
      - apache_cis_section1
  tags:
      - level 1
      - level 2
      - notscored
      - audit
      - rule_1.1

- name: "NOTSCORED | 1.2 | AUDIT | Ensure the Server Is Not a Multi-Use System"
  block:
      - name: "NOT SCORED | 1.2 | AUDIT | Ensure the Server Is Not a Multi-Use System | Gather running services for review"
        command: systemctl list-units --type=service --no-pager
        changed_when: false
        failed_when: false
        register: apache_ubuntu_1_2_running_services

      - name: "NOTSCORED | 1.2 | AUDIT | Ensure the Server Is Not a Multi-Use System | Display running services"
        debug:
            msg:
                - "Warning! Below are the running services. Please review"
                - "Servers should only be single service"
                - "{{ apache_ubuntu_1_2_running_services.stdout_lines }}"
  when:
      - apache_cis_1_2
      - apache_cis_section1
  tags:
      - level1
      - level2
      - notscored
      - audit
      - rule_1.2