---
# Section 1 Fixes
- name: "NOTSCORED | 1.1 | AUDIT | Ensure the Pre-Installation Planning Checklist Has Been Implemented"
  debug:
      msg:
          - "Warning! Make sure you have your pre-installation checklist completed"
          - "Please refer to control 1.1 in the benchmark document for those items"
  when:
      - apache_cis_1_1
      - apache_cis_section1
  tags:
      - level 1
      - level 2
      - notscored
      - audit
      - rule_1.1

- name: "NOTSCORED | 1.2 | AUDIT | Ensure the Server Is Not a Multi-Use System"
  block:
      - name: "NOT SCORED | 1.2 | AUDIT | Ensure the Server Is Not a Multi-Use System | Gather running services for review"
        command: systemctl list-units --type=service --no-pager
        changed_when: false
        failed_when: false
        register: apache_ubuntu_1_2_running_services

      - name: "NOTSCORED | 1.2 | AUDIT | Ensure the Server Is Not a Multi-Use System | Display running services"
        debug:
            msg:
                - "Warning! Below are the running services. Please review"
                - "Servers should only be single service"
                - "{{ apache_ubuntu_1_2_running_services.stdout_lines }}"
  when:
      - apache_cis_1_2
      - apache_cis_section1
  tags:
      - level1
      - level2
      - notscored
      - audit
      - rule_1.2

- name: "NOTSCORED | 1.3 | PATCH | Ensure Apache Is Installed From the Appropriate Binaries"
  apt:
      name: apache2
      state: present
  when:
      - apache_cis_1_1
      - apache_cis_section1
      - apache_cis_disruption_high
  tags:
      - level1
      - level2
      - notscored
      - audit
      - rule_1.3

# Section 2 Fixes
- name: "NOTSCORED | 2.1 | AUDIT | Ensure Only Necessary Authentication and Authorization Modules Are Enabled"
  block:
      - name: "NOT SCORED | 2.1 | AUDIT | Ensure Only Necessary Authentication and Authorization Modules Are Enabled | Capture Auth modules"
        shell: apache2ctl -M
        changed_when: false
        failed_when: false
        register: apache_ubuntu_2_1_loaded_modules

      - name: "NOTSCORED | 2.1 | AUDIT | Ensure Only Necessary Authentication and Authorization Modules Are Enabled | Display Modules"
        debug:
            msg:
                - "Warning! Below are the installed modules. Please review and remove any un-needed modules"
                - "Auth Modules:"
                - "{{ apache_ubuntu_2_1_loaded_modules.stdout_lines }}"
  when:
      - apache_cis_2_1
      - apache_cis_section2
  tags:
      - level1
      - level2
      - notscored
      - audit
      - rule_2.1

- name: "SCORED | 2.2 | PATCH | Ensure the Log Config Module Is Enabled"
  block:
      - name: "SCORED | 2.2 | PATCH | Ensure the Log Config Module Is Enabled | Check to see if mod_log_config already exists"
        shell: apachectl -l | grep mod_log_config
        changed_when: false
        failed_when: false
        register: apache_ubuntu_mod_log_config_state

      - name: "SCORED | 2.2 | PATCH | Ensure the Log Config Module Is Enabled | Enable mod_log_config if not enabled"
        command: a2enmod mod_log_config
        changed_when: apache_ubuntu_mod_log_config_enabled.rc == 0
        failed_when: apache_ubuntu_mod_log_config_enabled.rc >=1
        register: apache_ubuntu_mod_log_config_enabled
        when: apache_ubuntu_mod_log_config_state == ""
  when:
      - apache_cis_2_2
      - apache_cis_section2
  tags:
      - level1
      - level2
      - scored
      - patch
      - rule_2.2
