---
- name: Install Apache
  block:
      - name: Install httpd RHEL7 based
        yum:
            name: httpd
            state: present
        when: ansible_facts.distribution_file_variety == "RedHat" and ansible_facts.distribution_major_version == "7"

      - name: Install httpd RHEL8 based
        dnf:
            name: httpd
            state: present
        when: ansible_facts.distribution_file_variety == "RedHat" and ansible_facts.distribution_major_version == "8"

      - name: Install Apache2
        apt:
            name: apache2
            state: present
        when: ansible_distribution_file_variety == "Debian"

      - name: Start httpd
        service:
            name: httpd
            state: started
        when: ansible_facts.distribution_file_variety == "RedHat"

      - name: Start Apache2
        service:
            name: apache2
            state: started
        when: ansible_distribution_file_variety == "Debian"
  when: automate_install

# - name: Add additional RHEL repo
#   command: subscription-manager repos --enable rhel-7-server-optional-rpms
#   when: ansible_facts.distribution_file_variety == "RedHat" and ansible_facts.distribution_major_version == "7"

- name: Install needed packages
  block:
      - name: Install RHEL 8 based packages
        dnf:
            name: ['mod_session', 'mod_ssl', 'apr-util-openssl', 'python3-lxml']
            state: present
        when: ansible_facts.distribution_file_variety == "RedHat" and ansible_facts.distribution_major_version == "8"

      - name: Install RHEL 7 based packages
        yum:
            name: ['mod_session', 'mod_ssl', 'apr-util-openssl', 'python-lxml, pyOpenSSL, python2-cryptography,libselinux-python,policycoreutils-python']
            state: present
        when: ansible_facts.distribution_file_variety == "RedHat" and ansible_facts.distribution_major_version == "7"

      - name: Install Ubuntu based packages
        apt:
            name: ['python-lxml', 'auditd']
            state: present
        when: ansible_facts.distribution_file_variety == "Debian" and ansible_facts.distribution_major_version == "20"

- name: Get ServerRoot folder
  # shell: cat /etc/httpd/conf/httpd.conf | grep 'ServerRoot "' | cut -f2 -d'"'
  shell: grep 'ServerRoot "' /etc/httpd/conf/httpd.conf | cut -f2 -d'"'
  changed_when: false
  failed_when: false
  register: apache_cis_server_root_dir_gather

- name: Get DocumentRoot folder
  shell: cat /etc/httpd/conf/httpd.conf | grep "DocumentRoot " | cut -f2 -d'"'
  changed_when: false
  failed_when: false
  register: apache_cis_doc_root_dir_gather

- name: Install policycoreutils-python-utils
  block:
      - name: Install policycoreutils-python-utils RHEL 8
        dnf:
            name: policycoreutils-python-utils
            state: present
        when: ansible_facts.distribution_file_variety == "RedHat" and ansible_facts.distribution_major_version == "8"

      - name: Install policycoreutils-python-utils RHEL 7 and lower
        yum:
            name: policycoreutils-python-utils
            state: present
        when: ansible_facts.distribution_file_variety == "RedHat" and ansible_facts.distribution_major_version == "8"
  when:
      - apache_cis_11_2
      - apache_cis_section11